language: bash

# we test at Trusty (14.04 (LTS))
# see https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

before_install:
  - _scripts/travis-install-tl.sh
  # refresh PATH variable
  - . /etc/environment
  # latexmk has to be installed after install-tl-ubuntu to ensure that texlive is not taken from debian, but the latest one. In other words: addons->apt->packages cannot be used
  - sudo apt-get install -y latexmk

script: latexmk

cache:
  directories:
    - /opt/texbin
    - /usr/local/texlive
